### ISSUE TITLE
Build fails: missing Shlomif_Common.cmake

### ISSUE THREAD

**Issue by scresante** [shlomif/fc-solve#15]
cmake fails with: 
`$ cmake .
CMake Error at CMakeLists.txt:5 (INCLUDE):
  INCLUDE could not find load file:

    Shlomif_Common

CMake Error at CMakeLists.txt:7 (SHLOMIF_COMMON_SETUP):
  Unknown CMake command "SHLOMIF_COMMON_SETUP".
`
The needed file is ignored in .gitignore but after digging through the git history I found it in your bitbucket. Cloning that and copying the needed file, and now I have a different problem, perl dependencies.

**Comment by shlomif** [comment]
Hi @scresante ! Thanks for your report and your interest in Freecell Solver. `Shlomif_Common.cmake` is mentioned in INSTALL.txt and other places, but since this is an often reported problem, I guess I'll have to comply with the advice at https://www.joelonsoftware.com/2007/02/19/seven-steps-to-remarkable-customer-service/ and permanently fix it. This seems doable using the include options at https://cmake.org/cmake/help/v3.0/command/include.html , as well as cmake's `FILE (download)` option.

Regarding the Perl dependencies - they should not be hard to install by reading these pages  - http://perl-begin.org/topics/cpan/wrappers-for-distributions/ and http://perl-begin.org/topics/cpan/ - and you can look at the `.travis.yml` and `appveyor.yml` files for some hints. I don't expect Freecell Solver to ever be deployable on a system where perl 5 and the CPAN modules it uses are not installable, so depending on them for the build and the tests is not an issue.

**Comment by shlomif** [comment]
@scresante : please test the latest commit to master and let me know if it resolves your problem.

**Comment by shlomif** [comment]
@scresante : please reply.

**Comment by shlomif** [comment]
Cloding this issue for now due to lack of response. I can reopen it later if needed.
